#!/usr/bin/env python

import argparse
import re
import sys
import time

from selenium import webdriver

argparser = argparse.ArgumentParser()
argparser.add_argument(
    "song",
    type=str,
    nargs="+",
    help="Name of the song to play"
)
args = argparser.parse_args()

profile = webdriver.firefox.firefox_profile.FirefoxProfile()
profile.set_preference("dom.webnotifications.enabled", False)
profile.add_extension("uBlock0_1.18.2.firefox.xpi")

options = webdriver.firefox.options.Options()
options.headless = True

driver = webdriver.Firefox(
    firefox_profile=profile,
    options=options
)

duration_pattern = re.compile(r"(?:(\d+))(?:\:(\d+))?(?:\:(\d+))?")

try:
    driver.get(f"https://www.youtube.com/results?search_query={' '.join(args.song)}")
    driver.find_elements_by_tag_name("ytd-video-renderer")[0].click()
    time.sleep(2)
    duration_element = driver.find_element_by_css_selector("span[class='ytp-time-duration']")
    title = driver.title[:-10]
    print(f"{title}")
    print(f"Duration: {duration_element.text}")
    match = duration_pattern.match(duration_element.text)
    g1, g2, g3 = match.group(1), match.group(2), match.group(3)
    if not g3:
        duration = int(g1) * 60 + int(g2)
    else:
        duration = int(g1) * 3600 + int(g2) * 60 + int(g3)
    time.sleep(duration)
except KeyboardInterrupt:
    pass
finally:
    driver.quit()
